// ── INTERNATIONALISATION (EN / PT) ────────────────────────────────────────
// To add a language: duplicate one of the locale objects below and add a
// button in index.html that calls setLang('xx').

const TR = {
  en: {
    nav_dates: "Dates",
    nav_fin: "Finance",
    nav_hr: "HR",
    nav_conv: "Converters",
    nav_tools: "Tools",
    hero_tag: "Free · No signup · Works worldwide",
    hero_h1a: "Every calculator",
    hero_h1b: "you'll ever need",
    hero_p: "The complete universe of calculators — free, no account needed.",
    search_ph: "Search calculators…",
    search_none: "No results for",
    sec_dates: "Dates & Time",
    sec_fin: "Finance",
    sec_hr: "HR — Brazil",
    sec_conv: "Converters",
    sec_tools: "Tools",
    badge_pop: "Popular",
    badge_new: "New",
    c_bd_t: "Business Days",
    c_bd_d: "Working days between two dates, excluding holidays.",
    c_cal_t: "Holiday Calendar 2026",
    c_cal_d: "Interactive calendar with all 2026 national holidays.",
    c_diff_t: "Date Difference",
    c_diff_d: "Years, months, weeks, days and hours between two dates.",
    c_dl_t: "Deadline Calculator",
    c_dl_d: "Add business days to a date to find the due date.",
    c_age_t: "Age Calculator",
    c_age_d: "Exact age in years, months and days + next birthday.",
    c_int_t: "Interest Calculator",
    c_int_d: "Simple & compound interest with monthly table.",
    c_disc_t: "Discount Calculator",
    c_disc_d: "Enter price + discount % to see final amount.",
    c_inst_t: "Installment Simulator",
    c_inst_d: "Installment value and total cost with or without interest.",
    c_perc_t: "Percentage Calculator",
    c_perc_d: "X% of Y · X is what % of Y · % change.",
    c_vac_t: "Vacation Pay",
    c_vac_d: "Gross/net vacation with 1/3 bonus and INSS.",
    c_13_t: "13th Salary",
    c_13_d: "Proportional 13th salary, 1st and 2nd installments.",
    c_ot_t: "Overtime",
    c_ot_d: "50% weekday and 100% Sunday/holiday rates.",
    c_inss_t: "INSS 2025",
    c_inss_d: "Progressive INSS with effective rate and FGTS.",
    c_cur_t: "Currency Converter",
    c_cur_d: "Live exchange rates between major world currencies.",
    c_bmi_t: "BMI Calculator",
    c_bmi_d: "Body Mass Index with WHO classification.",
    c_num_t: "Number Converter",
    c_num_d: "Fractions ↔ decimals ↔ percentages.",
    c_unit_t: "Unit Converter",
    c_unit_d: "Length, weight, temperature and volume.",
    c_csv_t: "CSV → JSON",
    c_csv_d: "Paste CSV and convert to formatted JSON instantly.",
    c_pw_t: "Password Generator",
    c_pw_d: "Strong random passwords with custom complexity.",
    c_b64_t: "Base64 Encoder",
    c_b64_d: "Encode or decode any text to/from Base64.",
    c_lorem_t: "Lorem Ipsum",
    c_lorem_d: "Generate placeholder paragraphs for mockups.",
    lbl_s: "Start date",
    lbl_e: "End date",
    lbl_bd: "Business days",
    lbl_td: "Total days",
    lbl_hl: "Holidays",
    lbl_wk: "Weekends",
    lbl_tod: "Today",
    lbl_hs: "Holiday/Sun",
    lbl_yr: "Years",
    lbl_mo: "Months",
    lbl_wk2: "Weeks",
    lbl_dy: "Days",
    lbl_nbd: "Business days to add",
    lbl_due: "Due date",
    lbl_dob: "Date of birth",
    dp_hint: "Click to pick or type MM/DD/YYYY",
    lbl_prin: "Principal",
    lbl_rate: "Rate %/month",
    lbl_per: "Months",
    lbl_fin: "Final",
    lbl_ti: "Interest",
    lbl_rt: "Return",
    lbl_op: "Original price",
    lbl_dp: "Discount (%)",
    lbl_fp: "Final price",
    lbl_sv: "You save",
    lbl_amt: "Amount",
    lbl_ins: "Installments",
    lbl_mr: "Monthly rate (%) — 0 for free",
    lbl_pi: "Per installment",
    lbl_tp: "Total paid",
    lbl_su: "Surcharge",
    lbl_of: "of",
    lbl_ofy: "of Y",
    lbl_fr: "From",
    lbl_to: "To",
    tab_chg: "% Change",
    lbl_sal: "Gross salary (R$)",
    lbl_vd: "Vacation days",
    lbl_s10: "Sell 10 days?",
    opt_no: "No",
    opt_yes: "Yes",
    lbl_vg: "Vacation gross",
    lbl_al: "Vacation bonus (1/3)",
    lbl_net: "Net to receive",
    lbl_mw: "Months worked",
    lbl_g13: "Gross 13th salary",
    lbl_1st: "1st Nov",
    lbl_2nd: "2nd net Dec",
    lbl_tn: "Total net",
    lbl_mh: "Monthly hours",
    lbl_h5: "Extra hours 50%",
    lbl_h1: "Extra hours 100%",
    lbl_hv: "Hour value",
    lbl_et: "Extra total",
    lbl_ts: "Total salary w/ OT",
    lbl_id: "INSS deduction",
    lbl_er: "Eff. rate",
    lbl_ns: "Net salary",
    th_br: "Bracket",
    th_rt: "Rate",
    th_dc: "Deduction",
    lbl_loading: "Loading rates...",
    lbl_wt: "Weight (kg)",
    lbl_ht: "Height (cm)",
    tab_si: "Simple",
    tab_ci: "Compound",
    tab_fd: "Frac→Dec",
    tab_df: "Dec→Frac",
    tab_pd: "%↔Dec",
    tab_len: "Length",
    tab_wt: "Weight",
    tab_tmp: "Temp.",
    tab_vol: "Volume",
    lbl_val: "Value",
    lbl_dec: "Decimal",
    lbl_num: "Numerator",
    lbl_den: "Denominator",
    lbl_len: "Length",
    lbl_csv: "Paste CSV",
    lbl_len2: "Length",
    lbl_typ: "Type",
    opt_all: "Letters, numbers & symbols",
    opt_an: "Letters & numbers",
    opt_n: "Numbers only",
    opt_a: "Letters only",
    lbl_in: "Input",
    lbl_out: "Output",
    lbl_pars: "Paragraphs",
    lbl_lw: "Start with Lorem ipsum?",
    btn_c: "Calculate",
    btn_cv: "Convert",
    btn_gen: "Generate",
    btn_cp: "📋 Copy",
    lbl_upload_csv: "Upload .csv",
    lbl_upload_file: "Upload file",
    btn_enc: "Encode",
    btn_dec: "Decode",
    btn_rg: "🔄 New",
    pw_click: "Click generate",
    th_m: "Mo.",
    th_i: "Interest",
    th_a: "Acc.",
    th_b: "Balance",
    footer: "Free calculators & tools for everyone · No signup required",
    footer_suggest: "Suggestions or want a new calculator?",
    footer_contact: "Get in touch",
    c_doc2pdf_t: "Doc → PDF",
    c_doc2pdf_d: "Convert DOCX or CSV files to PDF instantly.",
    lbl_d2p_docx: "Word file (.docx)",
    lbl_d2p_drop: "Drop or click to select .docx",
    lbl_d2p_drop_csv: "Drop or click to select .csv",
    lbl_d2p_csv: "CSV file",
    lbl_d2p_title: "PDF Title",
    lbl_d2p_gen: "Generate PDF",
    c_das_t: "DAS Calculator",
    c_das_d: "MEI fixed DAS and Simples Nacional by annex.",
    c_prol_t: "Pró-labore",
    c_prol_d: "Legal minimum, INSS and net based on minimum wage.",
    c_resc_t: "Rescisão CLT",
    c_resc_d: "Dismissal calculator — salary, vacation, 13th and FGTS.",
    c_irrf_t: "IRRF Salary",
    c_irrf_d: "Income tax withheld on salary 2025.",
    c_imgconv_t: "Image Converter",
    c_imgconv_d: "Convert images between JPG, PNG, WEBP — locally.",
    c_short_t: "URL Shortener",
    c_short_d: "Shorten any link instantly via TinyURL.",
    das_mei_info: "MEI — fixed monthly DAS 2025. Choose your activity:",
    das_act: "Activity",
    das_com: "Commerce / Industry",
    das_svc: "Services",
    das_both: "Commerce + Services",
    das_emp: "Has employee?",
    das_emp_lbl: "Employee FGTS",
    das_aliq: "Nominal rate",
    das_ef: "Effective rate",
    das_liq: "Net revenue",
    das_rev12: "Gross revenue 12m (R$)",
    das_rev_m: "Month revenue (R$)",
    das_annex: "Annex",
    prol_sm_ref: "Current minimum wage",
    prol_sal: "Pro-labore gross (R$)",
    prol_sm: "Minimum wage (reference)",
    prol_min: "Legal minimum (28%)",
    prol_pct: "% of min. wage",
    rs_months: "Months worked",
    rs_days: "Days worked in month",
    rs_type: "Dismissal type",
    rs_sem: "Without cause (by employer)",
    rs_ped: "Resignation",
    rs_justa: "For cause",
    rs_comum: "Mutual agreement (art. 484-A)",
    rs_fgts_bal: "FGTS balance (R$)",
    rs_saldo: "Salary balance",
    rs_ferias: "Vacation + 1/3",
    rs_13: "13th proportional",
    rs_multa: "FGTS fine",
    rs_bruto: "Total gross",
    rs_liquido: "Total net (- INSS)",
    ir_dep: "Dependents",
    ir_ded_dep: "Dependent deduction",
    ir_base: "Tax base",
    ir_aliq: "Rate",
    ir_faixa: "Bracket",
    ir_ded: "Deduction",
    imgc_src: "Source image",
    imgc_drop: "Drop or click to upload image",
    imgc_fmt: "Convert to",
    imgc_q: "Quality (JPG/WEBP)",
    imgc_go: "Convert & Download",
    short_url: "Long URL",
    short_go: "Shorten",
    short_result: "Shortened link",
    short_open_lbl: "Shortened link",
    short_copied: "Copied to clipboard!",
    lbl_total: "Total",
    c_liq_t: "Net Salary",
    c_liq_d:
      "All deductions: INSS, IRRF, FGTS, transport, health plan and more.",
    liq_outros: "Other deductions (R$)",
    liq_opt: "Benefits deducted from payroll (optional)",
    liq_vt: "Transport voucher (R$)",
    liq_vr: "Meal/food voucher (R$)",
    liq_ps: "Health plan (R$)",
    liq_pd: "Dental plan (R$)",
    liq_prev: "Private pension (R$)",
    liq_cons: "Payroll loan (R$)",
    liq_res: "Net salary to receive",
    liq_tot_desc: "Total deducted",
    liq_comp: "Gross salary breakdown",
    liq_item: "Item",
    liq_val: "Amount",
    liq_pct_sal: "% of gross",
    months: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    days: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    wdays: [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
  },

  pt: {
    nav_dates: "Datas",
    nav_fin: "Financeiro",
    nav_hr: "RH",
    nav_conv: "Conversores",
    nav_tools: "Ferramentas",
    hero_tag: "Gratuito · Sem cadastro · Para todos",
    hero_h1a: "Todas as calculadoras",
    hero_h1b: "que você vai precisar",
    hero_p: "O universo completo de cálculos — grátis, sem cadastro.",
    search_ph: "Buscar calculadoras…",
    search_none: "Nenhum resultado para",
    sec_dates: "Datas & Tempo",
    sec_fin: "Financeiro",
    sec_hr: "RH — Brasil",
    sec_conv: "Conversores",
    sec_tools: "Ferramentas",
    badge_pop: "Popular",
    badge_new: "Novo",
    c_bd_t: "Dias Úteis",
    c_bd_d: "Dias úteis entre duas datas, excluindo feriados.",
    c_cal_t: "Calendário de Feriados 2026",
    c_cal_d: "Calendário interativo com todos os feriados nacionais de 2026.",
    c_diff_t: "Diferença entre Datas",
    c_diff_d: "Anos, meses, semanas, dias e horas entre duas datas.",
    c_dl_t: "Calculadora de Prazo",
    c_dl_d: "Some dias úteis a uma data para encontrar o vencimento.",
    c_age_t: "Calculadora de Idade",
    c_age_d: "Idade exata em anos, meses e dias + próximo aniversário.",
    c_int_t: "Calculadora de Juros",
    c_int_d: "Juros simples e compostos com tabela mensal.",
    c_disc_t: "Calculadora de Desconto",
    c_disc_d: "Informe o preço e desconto % para ver o valor final.",
    c_inst_t: "Simulador de Parcelamento",
    c_inst_d: "Valor da parcela e total pago com ou sem juros.",
    c_perc_t: "Calculadora de Porcentagem",
    c_perc_d: "X% de Y · X é que % de Y · variação %.",
    c_vac_t: "Calculadora de Férias",
    c_vac_d: "Férias brutas/líquidas com 1/3 e INSS.",
    c_13_t: "13º Salário",
    c_13_d: "13º proporcional dividido em 1ª e 2ª parcelas.",
    c_ot_t: "Horas Extras",
    c_ot_d: "50% dias úteis e 100% domingos/feriados.",
    c_inss_t: "INSS 2025",
    c_inss_d: "Tabela progressiva com alíquota efetiva e FGTS.",
    c_cur_t: "Conversor de Moeda",
    c_cur_d: "Taxas ao vivo entre as principais moedas do mundo.",
    c_bmi_t: "Calculadora de IMC",
    c_bmi_d: "Índice de Massa Corporal com classificação OMS.",
    c_num_t: "Conversor de Números",
    c_num_d: "Frações ↔ decimais ↔ porcentagens.",
    c_unit_t: "Conversor de Unidades",
    c_unit_d: "Comprimento, peso, temperatura e volume.",
    c_csv_t: "CSV → JSON",
    c_csv_d: "Cole CSV e converta para JSON formatado.",
    c_pw_t: "Gerador de Senha",
    c_pw_d: "Senhas aleatórias fortes com complexidade personalizada.",
    c_b64_t: "Codificador Base64",
    c_b64_d: "Codifique ou decodifique qualquer texto em Base64.",
    c_lorem_t: "Lorem Ipsum",
    c_lorem_d: "Gere parágrafos placeholder para mockups.",
    lbl_s: "Data inicial",
    lbl_e: "Data final",
    lbl_bd: "Dias úteis",
    lbl_td: "Total de dias",
    lbl_hl: "Feriados",
    lbl_wk: "Fins de semana",
    lbl_tod: "Hoje",
    lbl_hs: "Feriado/Dom",
    lbl_yr: "Anos",
    lbl_mo: "Meses",
    lbl_wk2: "Semanas",
    lbl_dy: "Dias",
    lbl_nbd: "Dias úteis a somar",
    lbl_due: "Data de vencimento",
    lbl_dob: "Data de nascimento",
    dp_hint: "Clique para escolher ou digite DD/MM/AAAA",
    lbl_prin: "Capital inicial (R$)",
    lbl_rate: "Taxa % ao mês",
    lbl_per: "Meses",
    lbl_fin: "Montante",
    lbl_ti: "Juros",
    lbl_rt: "Rentabilidade",
    lbl_op: "Preço original (R$)",
    lbl_dp: "Desconto (%)",
    lbl_fp: "Preço final",
    lbl_sv: "Você economiza",
    lbl_amt: "Valor total (R$)",
    lbl_ins: "Parcelas",
    lbl_mr: "Taxa ao mês (%) — 0 sem juros",
    lbl_pi: "Por parcela",
    lbl_tp: "Total pago",
    lbl_su: "Acréscimo",
    lbl_of: "de",
    lbl_ofy: "de Y",
    lbl_fr: "De",
    lbl_to: "Para",
    tab_chg: "Variação %",
    lbl_sal: "Salário bruto (R$)",
    lbl_vd: "Dias de férias",
    lbl_s10: "Vender 10 dias?",
    opt_no: "Não",
    opt_yes: "Sim",
    lbl_vg: "Férias brutas",
    lbl_al: "Abono pecuniário",
    lbl_net: "Valor líquido a receber",
    lbl_mw: "Meses trabalhados",
    lbl_g13: "13º bruto",
    lbl_1st: "1ª parcela (Nov)",
    lbl_2nd: "2ª líquida (Dez)",
    lbl_tn: "Total líquido",
    lbl_mh: "Horas mensais",
    lbl_h5: "Horas extras 50%",
    lbl_h1: "Horas extras 100%",
    lbl_hv: "Valor da hora",
    lbl_et: "Total extras",
    lbl_ts: "Salário total c/ extras",
    lbl_id: "Desconto INSS",
    lbl_er: "Alíquota efetiva",
    lbl_ns: "Salário líquido",
    th_br: "Faixa",
    th_rt: "Alíquota",
    th_dc: "Desconto",
    lbl_loading: "Carregando taxas...",
    lbl_wt: "Peso (kg)",
    lbl_ht: "Altura (cm)",
    tab_si: "Simples",
    tab_ci: "Compostos",
    tab_fd: "Fração→Dec",
    tab_df: "Dec→Fração",
    tab_pd: "%↔Dec",
    tab_len: "Comprimento",
    tab_wt: "Peso",
    tab_tmp: "Temperatura",
    tab_vol: "Volume",
    lbl_val: "Valor",
    lbl_len2: "Comprimento",
    lbl_dec: "Decimal",
    lbl_num: "Numerador",
    lbl_den: "Denominador",
    lbl_len: "Comprimento",
    lbl_csv: "Cole seu CSV aqui",
    lbl_typ: "Tipo",
    opt_all: "Letras, números e símbolos",
    opt_an: "Letras e números",
    opt_n: "Apenas números",
    opt_a: "Apenas letras",
    lbl_in: "Entrada",
    lbl_out: "Saída",
    lbl_pars: "Parágrafos",
    lbl_lw: 'Iniciar com "Lorem ipsum"?',
    btn_c: "Calcular",
    btn_cv: "Converter",
    btn_gen: "Gerar",
    btn_cp: "📋 Copiar",
    lbl_upload_csv: "Enviar .csv",
    lbl_upload_file: "Enviar arquivo",
    btn_enc: "Codificar",
    btn_dec: "Decodificar",
    btn_rg: "🔄 Novo",
    pw_click: "Clique em gerar",
    th_m: "Mês",
    th_i: "Juros",
    th_a: "Acum.",
    th_b: "Saldo",
    footer: "Calculadoras e ferramentas gratuitas para todos · Sem cadastro",
    footer_suggest: "Sugestões ou quer uma nova calculadora?",
    footer_contact: "Entre em contato",
    c_doc2pdf_t: "Doc → PDF",
    c_doc2pdf_d: "Converta arquivos DOCX ou CSV para PDF.",
    lbl_d2p_docx: "Arquivo Word (.docx)",
    lbl_d2p_drop: "Arraste ou clique para selecionar .docx",
    lbl_d2p_drop_csv: "Arraste ou clique para selecionar .csv",
    lbl_d2p_csv: "Arquivo CSV",
    lbl_d2p_title: "Título do PDF",
    lbl_d2p_gen: "Gerar PDF",
    c_das_t: "Calculadora DAS",
    c_das_d: "DAS fixo MEI e Simples Nacional por Anexo.",
    c_prol_t: "Pró-labore",
    c_prol_d: "Mínimo legal, INSS e líquido baseado no salário mínimo.",
    c_resc_t: "Rescisão CLT",
    c_resc_d: "Saldo, férias, 13º e multa FGTS por tipo de desligamento.",
    c_irrf_t: "IRRF Salário",
    c_irrf_d: "Imposto de renda retido na fonte sobre salário 2025.",
    c_imgconv_t: "Conversor de Imagem",
    c_imgconv_d: "Converta imagens entre JPG, PNG, WEBP — localmente.",
    c_short_t: "Encurtador de Link",
    c_short_d: "Encurte qualquer URL via TinyURL.",
    das_mei_info: "MEI — DAS mensal fixo 2025. Selecione sua atividade:",
    das_act: "Atividade",
    das_com: "Comércio / Indústria",
    das_svc: "Serviços",
    das_both: "Comércio + Serviços",
    das_emp: "Tem empregado?",
    das_emp_lbl: "FGTS Empregado",
    das_aliq: "Alíquota nominal",
    das_ef: "Alíquota efetiva",
    das_liq: "Receita líquida",
    das_rev12: "Receita bruta 12m (R$)",
    das_rev_m: "Receita do mês (R$)",
    das_annex: "Anexo",
    prol_sm_ref: "Salário mínimo vigente",
    prol_sal: "Pró-labore bruto (R$)",
    prol_sm: "Salário mínimo (referência)",
    prol_min: "Mínimo legal (28%)",
    prol_pct: "% do salário mínimo",
    rs_months: "Meses trabalhados",
    rs_days: "Dias trabalhados no mês",
    rs_type: "Tipo de rescisão",
    rs_sem: "Sem justa causa (pelo empregador)",
    rs_ped: "Pedido de demissão",
    rs_justa: "Com justa causa",
    rs_comum: "Acordo entre partes (art. 484-A)",
    rs_fgts_bal: "Saldo FGTS acumulado (R$)",
    rs_saldo: "Saldo salário",
    rs_ferias: "Férias + 1/3",
    rs_13: "13º proporcional",
    rs_multa: "Multa FGTS",
    rs_bruto: "Total bruto",
    rs_liquido: "Total líquido (- INSS)",
    ir_dep: "Dependentes",
    ir_ded_dep: "Dedução dependentes",
    ir_base: "Base de cálculo IR",
    ir_aliq: "Alíquota",
    ir_faixa: "Faixa",
    ir_ded: "Dedução",
    imgc_src: "Imagem de origem",
    imgc_drop: "Arraste ou clique para fazer upload",
    imgc_fmt: "Converter para",
    imgc_q: "Qualidade (JPG/WEBP)",
    imgc_go: "Converter e Baixar",
    short_url: "URL longa",
    short_go: "Encurtar",
    short_result: "Link encurtado",
    short_open_lbl: "Link encurtado",
    short_copied: "Copiado!",
    lbl_total: "Total",
    c_liq_t: "Salário Líquido",
    c_liq_d: "Todos os descontos: INSS, IRRF, FGTS, VT, plano de saúde e mais.",
    liq_outros: "Outros descontos (R$)",
    liq_opt: "Benefícios com desconto em folha (opcional)",
    liq_vt: "Vale-transporte (R$)",
    liq_vr: "Vale-refeição/alimentação (R$)",
    liq_ps: "Plano de saúde (R$)",
    liq_pd: "Plano dental (R$)",
    liq_prev: "Previdência privada (R$)",
    liq_cons: "Empréstimo consignado (R$)",
    liq_res: "Salário líquido a receber",
    liq_tot_desc: "Total descontado",
    liq_comp: "Composição do salário bruto",
    liq_item: "Item",
    liq_val: "Valor",
    liq_pct_sal: "% do bruto",
    months: [
      "Janeiro",
      "Fevereiro",
      "Março",
      "Abril",
      "Maio",
      "Junho",
      "Julho",
      "Agosto",
      "Setembro",
      "Outubro",
      "Novembro",
      "Dezembro",
    ],
    days: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
    wdays: [
      "domingo",
      "segunda-feira",
      "terça-feira",
      "quarta-feira",
      "quinta-feira",
      "sexta-feira",
      "sábado",
    ],
  },
};

// Restore saved language preference before any dpInit calls.
// Only sets L — full setLang() runs from the init script after all
// pickers are initialised (so dpBuf / DP / dpRender are all ready).
let L = (function () {
  try {
    const saved = localStorage.getItem("calcverse_lang");
    if (saved && (saved === "en" || saved === "pt")) return saved;
  } catch (_) {}
  return "en";
})();

function t(k) {
  return TR[L][k] || TR.en[k] || k;
}

function setLang(l) {
  L = l;
  document.documentElement.lang = l;
  document
    .querySelectorAll(".lbtn")
    .forEach((b) =>
      b.classList.toggle("on", b.textContent.trim() === l.toUpperCase()),
    );
  document
    .querySelectorAll("[data-i]")
    .forEach((el) => (el.textContent = t(el.dataset.i)));
  document
    .querySelectorAll("[data-i-placeholder]")
    .forEach((el) => (el.placeholder = t(el.dataset.iPlaceholder)));

  // Re-format datepicker inputs for the new locale.
  // Keeps existing selections — only the display format and placeholder change.
  const dpPh = l === "pt" ? "DD/MM/AAAA" : "MM/DD/YYYY";
  if (typeof DP !== "undefined") {
    Object.keys(DP).forEach((id) => {
      dpBuf[id] = ""; // clear any in-progress typed buffer
      const el = document.getElementById("dp-" + id);
      if (el) {
        el.value = DP[id].sel ? fmtD(DP[id].sel) : "";
        el.placeholder = dpPh;
        el.classList.remove("dpd-typing", "dpd-invalid");
      }
    });
    if (typeof dpClose === "function") dpClose();
    if (typeof dpRender === "function") dpRender();
  }

  if (typeof ecRender === "function") ecRender();

  // Persist the choice — survives page reloads without a round-trip to the server.
  try { localStorage.setItem("calcverse_lang", l); } catch (_) {}
}
